voc/urls.py
from django.contrib import admin
from django.urls import path
from vocapp import views

urlpatterns = [
	path('', views.index),
	path('test', views.test),
	path('test/', views.test),
	path('admin', admin.site.urls),
	path('word_in_progress/<str:pc_word>/', views.word_in_progress),
	path('add_new/<str:pc_new_word>/', views.add_new_with_parameter),
	path('add_new', views.add_new),
	path('add_new/', views.add_new),
	path('ready_list/', views.ready_list),
	path('next/<str:pc_last_word>/', views.next_with_last),
	path('next/', views.next),
	path('ready/<str:pc_ready_word>/', views.ready),
	path('unready/<str:pc_unready_word>/', views.unready),
	path('book/<str:pc_book>/<str:pc_paragraph>/', views.book),
	path('books/', views.books),

]

vocapp/models.py
from django.db import models

# Create your models here.
class Syllable(models.Model):
    word = models.TextField( verbose_name = 'Слово', default = '', unique = True, primary_key=True)
    transcription = models.TextField(null=True, verbose_name = 'Транскрипция', default = '', blank=True)
    translations = models.TextField(null=True, verbose_name = 'Переводы', default = '', blank=True)
    examples = models.TextField(null=True, verbose_name = 'Примеры', default = '', blank=True)
    show_count =models.IntegerField(null=True, verbose_name = 'Количество показов', default = 0)
    ready = models.IntegerField(null=True, verbose_name = 'Признак выученности', default = 0)
    last_view = models.DateTimeField(null=True, verbose_name='Дата/Время последнего просмотра', auto_now_add = True)

class Books(models.Model):
    id_book = models.AutoField(primary_key=True)
    book_name = models.TextField(null=True, verbose_name = 'Название книги', default = '', blank=True)
    current_paragraph = models.IntegerField(null=True, verbose_name='Текущий читаемый параграф', default=1)

class Paragraphs(models.Model):
    id_paragraph = models.AutoField(primary_key=True)
    id_book = models.IntegerField(null=True, verbose_name = 'Идентификатор книги', default = 0, blank=True)
    paragraph = models.TextField(null=True, verbose_name = 'Параграф книги', default = '', blank=True)

vocapp/views.py
from django.shortcuts import render, redirect
from django import forms
from .models import Syllable,Books,Paragraphs
#import sqlite3 as sl
import datetime
from datetime import date, timedelta
import load_syllable_from_wooordhunt
import os.path
import subprocess
import re
import hashlib
import threading

def test(request):
    return
    print(" ============== test")
    pc_file_path = r'C:\voc\voc\Blood_of_the_Fold_by_Terry_Goodkind_Goodkind,_Terry_z_lib_org.txt'
    lc_book_name = 'Blood of the Fold by Terry Goodkind'
    ll_book = open(pc_file_path, "r", encoding='utf8').readlines()
    lc_result = ''
    for lc_paragraph in ll_book:
        lc_result = lc_result + lc_paragraph.replace(chr(13), '').replace(chr(10), '').replace(chr(12), '')+chr(13)
    lc_result = lc_result.replace(chr(13)+chr(13),chr(13)).replace(chr(13)+chr(13),chr(13)).replace(chr(13)+chr(13),chr(13)).replace(chr(13)+chr(13),chr(13)).replace(chr(13)+chr(13),chr(13)).replace(chr(13)+chr(13),chr(13)).replace(chr(13)+chr(13),chr(13)).replace(chr(13)+chr(13),chr(13)).replace(chr(13)+chr(13),chr(13))
    ll_paragraps = lc_result.split(chr(13))

    book = Books(book_name = lc_book_name, current_paragraph = 1)
    book.save()


    for lc_p in ll_paragraps:
        print('==============================================')
        print(lc_p)
        if len(lc_p):
            paragraph = Paragraphs(id_book = book.id_book, paragraph = lc_p)
            paragraph.save()

    data = {"text":lc_result}
    return render(request, "test.html", context=data)


def index(request):
    print(" ============== index")
    syllable = Syllable.objects.filter(ready=0).order_by('last_view')
    data = {"words":syllable,"number_of_words_to_study":str(len(syllable)), 'number_of_words_learned':str(len(Syllable.objects.filter(ready=1))), "last_added_word":Syllable.objects.filter(ready=0).filter(show_count=0).order_by('-last_view')[0].word}
    return render(request, "index.html", context=data)

def ready_list(request):
    print(" ============== ready_list")
    syllable = Syllable.objects.filter(ready=1).order_by('last_view')
    data = {"words":syllable,"number_of_words_to_study":str(len(syllable)), 'number_of_words_learned':str(len(Syllable.objects.filter(ready=1))), "last_added_word":Syllable.objects.filter(ready=0).filter(show_count=0).order_by('-last_view')[0].word}
    return render(request, "ready_list.html", context=data)

# 'onchange':"document.getElementById('id_link_on_wooordhunt').href='https://wooordhunt.ru/word/'+escape(this.value)"
class UserForm(forms.Form):
    word = forms.CharField( label="Слово", widget=forms.TextInput(attrs={'class' : 'my_class_input_word'}))
    transcription = forms.CharField(label="Транскрипция", widget=forms.TextInput(attrs={'class' : 'my_class_input_transcription'} ))
    translations = forms.CharField(label="Перевод", widget=forms.Textarea(attrs={'class' : 'my_class_input_translations','rows':"7"} ))
    examples = forms.CharField(label="Примеры", widget=forms.Textarea(attrs={'class':"my_class_input_examples",'rows':"7"} ))





def add_new_with_parameter(request, pc_new_word):
    if request.method == "POST":
        if len(request.POST.get("translations"))>0:
            syllable = Syllable(word = request.POST.get("word").lower(), transcription = request.POST.get("transcription"), translations = request.POST.get("translations"), examples = request.POST.get("examples"), last_view = datetime.datetime.now())
            print(syllable.word, syllable.transcription, syllable.translations, syllable.examples, syllable.last_view)
            if len(syllable.word)>=3 and len(syllable.translations)>3:
                syllable.save()
                return redirect(index)
    lo_syllabble = Syllable.objects.get(word=pc_new_word)
    print(" >============== add_new_with_parameter:", pc_new_word, lo_syllabble)
    data = {"word":lo_syllabble.word, "transcription":lo_syllabble.transcription, "translations":lo_syllabble.translations, "examples":lo_syllabble.examples,"number_of_words_to_study":str(len(Syllable.objects.filter(ready=0))), 'number_of_words_learned':str(len(Syllable.objects.filter(ready=1))), "last_added_word":Syllable.objects.filter(ready=0).filter(show_count=0).order_by('-last_view')[0].word}
    return render(request, "add_new.html", context=data)


def add_new(request):
    print(" ====================add_new(request)")
    data = {'word': "", 'transcription': "", 'translations': "", 'examples': "", 'last_view': "","number_of_words_to_study":str(len(Syllable.objects.filter(ready=0))), 'number_of_words_learned':str(len(Syllable.objects.filter(ready=1))), "last_added_word":Syllable.objects.filter(ready=0).filter(show_count=0).order_by('-last_view')[0].word}
    if request.method == "POST":
        print("Количество полученных данных: ", len(Syllable.objects.filter(word=request.POST.get("word").lower())))
        if len(Syllable.objects.filter(word=request.POST.get("word").lower(), ready = 0))>0: # в том случае если слово уже есть в базе, загружаем его, а не загружаем
            return redirect(add_new_with_parameter, request.POST.get("word").lower())
        if len(request.POST.get("translations"))>0:
            syllable = Syllable(word = request.POST.get("word").lower(), transcription = request.POST.get("transcription"), translations = request.POST.get("translations"), examples = request.POST.get("examples"), last_view = datetime.datetime.now())
            print(syllable.word, syllable.transcription, syllable.translations, syllable.examples, syllable.last_view)
            if len(syllable.word)>=3 and len(syllable.translations)>3:
                syllable.save()
                return redirect(index)
        else:
            if len(request.POST.get("word"))>0:
                print(" ============== load_from_wooordhunt")
                print("load_from_wooordhunt:", request.POST.get("word"))
                #try:
                lo_wh = load_syllable_from_wooordhunt.Wooordhunt(r'https://wooordhunt.ru/word/' + request.POST.get("word").lower())
                data = {"word": request.POST.get("word").lower(), "transcription": lo_wh.get_transcription(),
                            "translations": lo_wh.get_translation(),
                            "examples": lo_wh.get_examples(),"number_of_words_to_study":str(len(Syllable.objects.filter(ready=0))), 'number_of_words_learned':str(len(Syllable.objects.filter(ready=1))), "last_added_word":Syllable.objects.filter(ready=0).order_by('-last_view')[0].word}
    else:
        if request.POST.get("word") != None:
            data = {'word':request.POST.get("word").lower(), transcription:'', translations:'', examples:'', last_view:'',"number_of_words_to_study":str(len(Syllable.objects.filter(ready=0))), 'number_of_words_learned':str(len(Syllable.objects.filter(ready=1))), "last_added_word":Syllable.objects.filter(ready=0).order_by('-last_view')[0].word }
        else:
            data = {'word':"", 'transcription':"", 'translations':"", 'examples':"", 'last_view':"","number_of_words_to_study":str(len(Syllable.objects.filter(ready=0))), 'number_of_words_learned':str(len(Syllable.objects.filter(ready=1))), "last_added_word":Syllable.objects.filter(ready=0).order_by('-last_view')[0].word}
    print('||||||||||||||||||||||||', data)
    return render(request, "add_new.html", context=data)



def add_format_for_russian(pc_source:str, lc_style_name): #возвращает строку, где русские символы переданной строки отмечены указанным стилем
    lc_russian = 'йцукенгшщзхъфывапролджэячсмитьбюё'
    lc_russian = lc_russian+lc_russian.upper()
    lc_result = ''
    for lc_chr in pc_source:
        if lc_chr in lc_russian:
            lc_result = lc_result + '<span class = "' + lc_style_name+'">' + lc_chr + '</span>'
        else:
            lc_result = lc_result + lc_chr
    return lc_result


def DownLoadExamples(pl_list):
    path_for_sounds = r'.\\vocapp\\static\\sounds\\examples\\'
    for part in pl_list:
        lc_example = part.split('\n')
        if len(lc_example[0])>10:
            lc_file_name = load_syllable_from_wooordhunt.Delete_from_String_all_Characters_Unsuitable_For_FileName(lc_example[0])
            lc_full_file_name = path_for_sounds + lc_file_name + '.mp3'
            if not os.path.exists(lc_full_file_name):
                try:
                    subprocess.run(["gtts-cli", lc_example[0], "--output", lc_full_file_name])
                    print('saved:', lc_full_file_name)
                except:
                    pass

def word_in_progress(request, pc_word):
    print(" ============== word_in_progress")
    print("wordinprogress:",pc_word)
    lo_syllabble = Syllable.objects.get(word=pc_word)

    lc_examples_html = lo_syllabble.examples
    #print(lc_examples_html.replace(chr(13),'|').replace(chr(10), '*') )
    if lc_examples_html[-2:]!=chr(13)+chr(10):
        lc_examples_html = lc_examples_html + chr(13)+chr(10)
        if lc_examples_html[-2:] != chr(13) + chr(10):
            lc_examples_html = lc_examples_html + chr(13) + chr(10)

    paragraphs = lc_examples_html.split(chr(13)+chr(10)+chr(13)+chr(10))
    path_for_sounds = r'.\\vocapp\\static\\sounds\\examples\\'
    lc_quote = '"'
    lc_str = ''
    #DownLoadExamples(paragraphs)
    thr1 = threading.Thread(target=DownLoadExamples, args=(paragraphs,)).start()
    for part in paragraphs:
        lc_example = part.split('\n')
        if len(lc_example[0])>10:
            lc_file_name = load_syllable_from_wooordhunt.Delete_from_String_all_Characters_Unsuitable_For_FileName(lc_example[0])
            #lc_full_file_name = path_for_sounds + lc_file_name + '.mp3'
            #if not os.path.exists(lc_full_file_name):
            #    try:
            #        subprocess.run(["gtts-cli", lc_example[0], "--output", lc_full_file_name])
            #        print('saved:', lc_full_file_name)
            #    except:
            #        pass

vocapp/templates/add_new.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    <link rel="shortcut icon" type="image/png" href="{% static '/images/favicon.ico' %}"/>
    <title>Добавление слова</title>
</head>

<body background="{% static 'images/background.gif' %}">
{% include "title.html" %}
<hr>

        <form method="POST" target="add_new/">{% csrf_token %}
                <div class="my_div_save">
                    <div class ='div_float_left'>    <IMG WIDTH="48" HEIGHT="48" src="{% static 'images/empty_32x32.png' %}"></div>
                    <div class ='div_float_left'><a onclick="javascript:history.back(); return false;"><IMG class ="image_little_button"  WIDTH="48" HEIGHT="48"  title = "Назад" src="{% static 'images/back.png' %}"></a></div>
                    <div class ='div_float_left'><IMG  WIDTH="48" HEIGHT="48" src="{% static 'images/empty_32x32.png' %}"></div>
                    <div class ='div_float_left'><a href="/"><IMG  class ="image_little_button"  WIDTH="48" HEIGHT="48"  title = "На главную" src="{% static 'images/home.png' %}"></a></div>
                    <div class ='div_float_left'><IMG  WIDTH="48" HEIGHT="48" src="{% static 'images/empty_32x32.png' %}"></div>
                    <div class ='div_float_right'><a id= 'id_link_on_wooordhunt' href="https://wooordhunt.ru/word/{{ word }}" target="_blank"><IMG  class ="image_little_button"  WIDTH="48" HEIGHT="48"  title = "wooordhunt.ru" src="{% static 'images/wh.ico' %}"></a></div>
                    <div class ='div_float_right'><IMG  WIDTH="48" HEIGHT="48" src="{% static 'images/empty_32x32.png' %}"></div>
                    <div class ='div_float_right'><a id= 'id_link_on_glosbe' href="https://ru.glosbe.com/en/ru/{{ word }}" target="_blank"><IMG  class ="image_little_button"  WIDTH="48" HEIGHT="48"  title = "wooordhunt.ru" src="https://ru.glosbe.com/assets/favicon/favicon-32x32.png"></a></div>
                    <div class ='div_float_right'><IMG  WIDTH="48" HEIGHT="48" src="{% static 'images/empty_32x32.png' %}"></div>
                    <input type="submit" value="Сохранить" class="button_save" onclick="new Audio( document.getElementById('invisible_link_for_link_path').getAttribute('href') ).play(); this.submit();">
                </div>
<hr>



        <table width = '100%' style="border: 0px;">

            <tr><th><label for="id_word">Слово:</label></th><td class = 'td_input_new_word'><input autocomplete="off" autofocus type="text" name="word" class="my_class_input_word" id="id_word" value ="{{ word }}" onchange="{document.getElementById('id_link_on_wooordhunt').href='https://wooordhunt.ru/word/'+escape(this.value)}"></td></tr>
            <tr><th><label for="id_transcription">Транскрипция:</label></th><td class = 'td_input_new_word'><input autocomplete="off" type="text" name="transcription" class="my_class_input_transcription" id="id_transcription" value = "{{ transcription }}"></td></tr>
            <tr><th><label for="id_translations">Перевод:</label></th><td class = 'td_input_new_word'><textarea autocomplete="off" name="translations" cols="40" rows="10" class="my_class_input_translations" id="id_translations">{{ translations }}</textarea></td></tr>
            <tr><th><label for="id_examples">Примеры:</label></th><td class = 'td_input_new_word'><textarea autocomplete="off" name="examples" cols="40" rows="10" class="my_class_input_examples" id="id_examples">{{ examples }}</textarea></td></tr>

        </table>

            <p align = "center"><input type="submit" value="Сохранить" class="button_save" onclick=" new Audio( document.getElementById('invisible_link_for_link_path').getAttribute('href') ).play(); this.submit();"></p>

        </form>


<a href = "{% static 'sounds' %}/{{ word }}.mp3" id="invisible_link_for_link_path"></a>

<!--
        <form method="POST" target="add_new/">{% csrf_token %}
        <table width = '100%'>
            {{ form.as_table }}
        </table>
            <p align = "center"><input type="submit" value="Сохранить" class="button"></p>
        </form>
-->
</body>

</html>













<script type="text/javascript">

function WordChange{document.getElementById('id_link_on_wooordhunt').href='https://wooordhunt.ru/word/'+escape(this.value)}



function getCookie(name) {
    let cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        const cookies = document.cookie.split(';');
        for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}

const csrftoken = getCookie('csrftoken');

</script>

vocapp/templates/book.html
<!DOCTYPE html>

{% load static %}
{% autoescape off %}
<html>
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    <link rel="shortcut icon" type="image/png" href="{% static '/images/favicon.ico' %}"/>
    <title>{{ book_name }}</title>
</head>


<body background="{% static 'images/background.gif' %}">

    <div class = 'my_div'>
        <div class="my_div_left">
            <div class="my_div_left">
                <p align="left"><span style="font-weight: bold;">{{ book_name }}</span></p>
            </div>
            <div class="my_div_right">

            </div>
            </div>
            <div class="my_div_right">
                <p align="right"><span style="font-weight: bold;">{{ in_book_position }}</span></p>
            </div>
    </div>

<hr>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>


    {{ text }}
    {% endautoescape %}


<br>
<br>
<hr>

    <div class = 'my_div' style="width: calc(100% - 10px); font-size:350%; font-weight: bold;">
        <a href="{{ link_on_start }}">
                <div class="my_div_left" style="width: calc(20% - 10px);">
                    <p>&lt;&lt;&lt;&laquo;</p>
                </div>
        </a>
        <a href="{{ link_on_prev }}">
            <div class="my_div_left" style="width: calc(20% - 10px);">
                <p>&lt;&lt;&lt;</p>
            </div>
        </a>

        <a href="{{ link_on_next }}">
            <div class="my_div_left" style="width: calc(20% - 10px);">
                <p>&gt;&gt;&gt;</p>
            </div>
        </a>
        <a href="{{ link_on_end }}">
                <div class="my_div_left" style="width: calc(20% - 10px);">
                    <p>&raquo;&gt;&gt;&gt;</p>
                </div>
        </a>
    </div>



<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>


</body>
</html>



<script type="text/javascript">

window.onload = function(event) {
    setLocation('#');
}
function setLocation(curLoc){
  location.href = curLoc;
  location.hash = curLoc;
}

</script>

vocapp/templates/books.html
<!DOCTYPE html>

{% load static %}

<html>
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    <link rel="shortcut icon" type="image/png" href="{% static '/images/favicon.ico' %}"/>
    <title>Books</title>
</head>


<body background="{% static 'images/background.gif' %}">


    <hr>
            <table   width = "100%">
                <tr>
                    <td style="border: 0px;" width="20%" align="center"><div class ='div_float_left'><a onclick="javascript:history.back(); return false;"><IMG class ="image_little_button"  WIDTH="48" HEIGHT="48"  title = "Назад" src="{% static 'images/back.png' %}"></a></div></td>
                    <td style="border: 0px;" width="40%" align="center"></td>
                    <td style="border: 0px;" width="40%" align="center"></td>

                </tr>
            </table>
    <hr>



    <table class="my_class_table_of_words" width = "100%">

    {% for book in books %}
    <tr>
        <td width="85%"><a href="/book/{{ book.id_book }}/{{ book.current_paragraph }}/">{{ book.book_name }}</a></td>
        <td with = "10%" style="color:Blue"> {{ book.current_paragraph }} </td>
    </tr>
    {% endfor %}
    </table>

    <hr>

</body>
</html>



<script type="text/javascript">

window.onload = function(event) {
    setLocation('#');
}
function setLocation(curLoc){
  location.href = curLoc;
  location.hash = curLoc;
}

</script>

vocapp/templates/index.html
<!DOCTYPE html>

{% load static %}

<html>
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    <link rel="shortcut icon" type="image/png" href="{% static '/images/favicon.ico' %}"/>
    <title>Memorier</title>
</head>


<body background="{% static 'images/background.gif' %}">

    {% include "title.html" %}

    <hr>
            <table   width = "100%">
                <tr>
                    <td style="border: 0px;" width="40%" align="center"><button class = 'button_add' onclick="window.location.href = './add_new/';">               Добавить слово               </button></td>
                    <td style="border: 0px;" width="40%" align="center"><button class = 'button_trained' onclick="window.location.href = './ready_list/';">               Выученные слова               </button></td>
                    <td style="border: 0px;" width="20%" align="center"><a href="./books/" style="margin:0px 0px 0px 0px"><IMG class ="image_little_button" style="display: inline-block;box-shadow: 2px 2px 3px 4px rgba(0,0,0,0.5);text-shadow: 1px 1px 2px black, 0 0 1em black; border-radius: 12px;" WIDTH="64" HEIGHT="64"  title = "Список книг" src="{% static 'images/books.png' %}"></a></td>
                </tr>
            </table>
    <hr>



    <table class="my_class_table_of_words" width = "100%">

    {% for word in words %}
    <tr>
        <td width="7%">{{ forloop.counter }}</td>
        <td with = "58%" style="color:Blue"><a href="./word_in_progress/{{ word.word }}/">{{ word.word }}</a></td>
        <td width="14%" align = "center" style="color:DarkRed"  onclick="new Audio( document.getElementById('invisible_link_for_link_path_{{ word.word }}').getAttribute('href') ).play(); return false;" >{{ word.transcription }}</td>
        <td width="7%" align = "center">{{ word.show_count }}</td>
        <td width="7%" align = "center"><a href="./add_new/{{ word.word }}/"><IMG class ="image_little_button" WIDTH="32" HEIGHT="32"  title = "Редактировать слово {{ word.word }}" src="{% static 'images/redo.png' %}"></a></td>
        <td width="7%" align = "center"><a href="/ready/{{ word.word }}/"><IMG  class ="image_little_button" WIDTH="32" HEIGHT="32"  title = "Слово выученно" src="{% static 'images/ok.png' %}"></a></td>
    </tr>
    {% endfor %}
    </table>

    <hr>

    {% for word in words %}
        <a href = "{% static 'sounds' %}/{{ word.word }}.mp3" id="invisible_link_for_link_path_{{ word.word }}"></a>
    {% endfor %}
</body>
</html>



<script type="text/javascript">

window.onload = function(event) {
    setLocation('#');
}
function setLocation(curLoc){
  location.href = curLoc;
  location.hash = curLoc;
}

</script>

vocapp/templates/ready_list.html
<!DOCTYPE html>

{% load static %}

<html>
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    <link rel="shortcut icon" type="image/png" href="{% static '/images/favicon.ico' %}"/>
    <title>Memorier</title>
</head>
<body background="{% static 'images/background.gif' %}">
{% include "title.html" %}
<hr>

    <div class = 'my_div'>
        <div class = 'my_div_left'>
        </div>
        <div class = 'my_div_right'>
            <button class = 'button_trained' onclick="window.location.href = '/';">Слова в процессе</button>
        </div>
    </div>
    <hr>

    <table class="my_class_table_of_words">
    {% for word in words %}
    <tr>
        <td width="65%"><a href="./word_in_progress/{{ word.word }}/">{{ word.word }}</a></td>
        <td width="14%" align = "center" style="color:DarkRed"  onclick="new Audio( document.getElementById('invisible_link_for_link_path_{{ word.word }}').getAttribute('href') ).play(); return false;" >{{ word.transcription }}</td>
        <td width="7%" align = "center">{{ word.show_count }}</td>
        <td width="7%" align = "center"><a href="/add_new/{{ word.word }}/"><IMG class ="image_little_button" WIDTH="32" HEIGHT="32"  title = "Редактировать слово {{ word.word }}" src="{% static 'images/redo.png' %}"></a></td>
        <td width="7%" align = "center"><a href="/unready/{{ word.word }}/"><IMG class ="image_little_button" WIDTH="32" HEIGHT="32"  title = "Вернуть слово в изучаемые" src="{% static 'images/return.png' %}"></a></td>
    </tr>
    {% endfor %}
    </table>
    <hr>
    {% for word in words %}
        <a href = "{% static 'sounds' %}/{{ word.word }}.mp3" id="invisible_link_for_link_path_{{ word.word }}"></a>
    {% endfor %}
</body>
</html>

vocapp/templates/test.html
<!DOCTYPE html>

{% load static %}

<html>
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    <link rel="shortcut icon" type="image/png" href="{% static '/images/favicon.ico' %}"/>
    <title>Test</title>
</head>


<body background="{% static 'images/background.gif' %}">
<PRE class = 'my_class_p_my_class_p_examples'>
{% autoescape off %}
{{ text }}
{% endautoescape %}
</PRE>>
</body>
</html>



<script type="text/javascript">
window.onload = function(event) {
    setLocation('#');
}
function setLocation(curLoc){
  location.href = curLoc;
  location.hash = curLoc;
}
</script>

vocapp/templates/title.html
{% load static %}
    <div class = 'my_div'>
        <div class="my_div_left">
            <div class="my_div_left">
                <p align="left">Количество слов на изучении: <span style="font-weight: bold;">{{ number_of_words_to_study }}</span></p>
            </div>
            <div class="my_div_right">
                <p align="rt">Последнее добавленное слово:<a href="./add_new/{{ last_added_word }}"><b>{{ last_added_word }}</b></a></p>
            </div>
        </div>
        <div class="my_div_right">
            <p align="right">Изучено слов: <span style="font-weight: bold;">{{ number_of_words_learned }}</span></p>
        </div>
    </div>